apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: v1ob5017a-nodejs
  janus-idp.io/tekton: v1ob5017a-nodejs
  backstage.io/kubernetes-id: v1ob5017a-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: v1ob5017a-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
